version: '3'
services:
  db_dev:
    image: postgres:latest
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev
    volumes:
      - ./containers/postgres/configs/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    expose:
      - '5432'
  demo-graphql:
    depends_on:
      - db_dev
    build:
      context: .
    environment:
      DB_HOST: db_dev
      DB_PORT: 5432
      DB_DATABASE: dev_db
      DB_SCHEMA: demo
      DB_USERNAME: admin
      DB_PASSWORD: dev
      DB_DRIVER: org.postgresql.Driver
    ports:
      - "8080:8080"
    expose:
      - '8080'