version: '3'
services:
  db_dev:
    image: postgres:latest
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev
    volumes:
      - ./containers/postgres/configs/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
  db_test:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
    volumes:
      - ./containers/postgres/configs/:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"
  app:
    build: .
    ports:
      - "8080:8080"