spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_DATABASE:dev_db}?currentSchema=${DB_SCHEMA:demo}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:dev}