spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        hbm2ddl.auto: none
  graphql:
    graphiql:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
